#!/bin/bash

set -e

SOURCES_DIR=/tmp/artifacts

unzip -q ${SOURCES_DIR}/${ADD_ONS_DISTRIBUTION_ZIP} -d ${SOURCES_DIR}

DISTRIBUTION_ZIP=${CONTROLLER_DISTRIBUTION_ZIP}
DISTRIBUTION_WAR_DIR=controller.war

unzip -q ${SOURCES_DIR}/${DISTRIBUTION_ZIP} -d ${SOURCES_DIR}

cp -rf ${SOURCES_DIR}/${DISTRIBUTION_WAR_DIR} ${JBOSS_HOME}/standalone/deployments/ROOT.war
touch ${JBOSS_HOME}/standalone/deployments/ROOT.war.dodeploy
cp -rf ${SOURCES_DIR}/SecurityPolicy/* ${JBOSS_HOME}/bin/


for dir in $JBOSS_HOME/bin $JBOSS_HOME/standalone; do
    chown -R jboss:root $dir
    chmod -R g+rwX $dir
done

# Create dir to remove JDBC driver
mkdir ${JBOSS_HOME}/modules/system/layers/openshift &> /dev/null || true
chown -R jboss:root ${JBOSS_HOME}/modules/system/layers/openshift

