#!/bin/bash
set -e

SOURCES_DIR=/tmp/artifacts

unzip -q ${SOURCES_DIR}/${ADD_ONS_DISTRIBUTION_ZIP} -d ${SOURCES_DIR}

DISTRIBUTION_WAR_DIR=dashbuilder-runtime.war

unzip -q ${SOURCES_DIR}/${DASHBUILDER_DISTRIBUTION_ZIP} -d ${SOURCES_DIR}

cp -rf ${SOURCES_DIR}/${DISTRIBUTION_WAR_DIR} ${JBOSS_HOME}/standalone/deployments/ROOT.war
touch ${JBOSS_HOME}/standalone/deployments/ROOT.war.dodeploy

for dir in $JBOSS_HOME/bin $JBOSS_HOME/standalone; do
    chown -R jboss:root $dir
    chmod -R g+rwX $dir
done

