#!/bin/bash
set -e

SOURCES_DIR=/tmp/artifacts

unzip -q ${SOURCES_DIR}/${ADD_ONS_DISTRIBUTION_ZIP} -d ${SOURCES_DIR}

DISTRIBUTION_WAR_DIR=dashbuilder-runtime.war

unzip -q ${SOURCES_DIR}/${DASHBUILDER_DISTRIBUTION_ZIP} -d ${SOURCES_DIR}

cp -rf ${SOURCES_DIR}/${DISTRIBUTION_WAR_DIR} ${JBOSS_HOME}/standalone/deployments/ROOT.war
touch ${JBOSS_HOME}/standalone/deployments/ROOT.war.dodeploy

chown -R jboss:root ${JBOSS_HOME}
chmod 0755 ${JBOSS_HOME}
chmod -R g+rwX ${JBOSS_HOME}

