#!/bin/bash

set -e

SOURCES_DIR=/tmp/artifacts

unzip -q ${SOURCES_DIR}/${BUSINESS_CENTRAL_DISTRIBUTION_ZIP} -d ${SOURCES_DIR}
chmod 0755 ${SOURCES_DIR}/${BUSINESS_CENTRAL_DISTRIBUTION_EAP}

cp -rf ${SOURCES_DIR}/${BUSINESS_CENTRAL_DISTRIBUTION_EAP}/* ${JBOSS_HOME}/
mv "${JBOSS_HOME}/standalone/deployments/business-central.war" "${JBOSS_HOME}/standalone/deployments/ROOT.war"
mv "${JBOSS_HOME}/standalone/deployments/business-central.war.dodeploy" "${JBOSS_HOME}/standalone/deployments/ROOT.war.dodeploy"

for dir in $JBOSS_HOME/bin $JBOSS_HOME/standalone; do
    chown -R jboss:root $dir
    chmod -R g+rwX $dir
done

# Create dir to remove JDBC driver
mkdir ${JBOSS_HOME}/modules/system/layers/openshift &> /dev/null || true
chown -R jboss:root ${JBOSS_HOME}/modules/system/layers/openshift

